export const termsPropertyManagementContent = `
# Homzhub Property Management – Terms and Conditions

1. **INTERPRETATIONS**
   1.1. The following definitions reflect the terms as used in the Agreement:
   1.2. "**Law**" or "**Laws**" shall mean all applicable statutes, enactments, acts of legislature, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives and orders of any Governmental Authority, tribunal, board, court of Nagpur, Maharashtra, India;
   1.3. "**Lease**" is any rental agreement whereby Owner has agreed to let and Tenant has agreed to accept the Property identified in the Lease in accordance with the terms of the Lease. The terms "lease", "tenant" and "rent" as used in this Agreement shall also mean and be read as "license", "licensee" and "license fee"/"fee", given that the Property may be let out either on lease or leave and license basis.
   1.4. "**Rent**" is the monthly amount that a Tenant is obligated to pay Owner pursuant to the terms of a Lease.
   1.5. **“Service(s)**” shall have the meaning as provided in Annexure B of this Agreement;
   1.6. "**Tenant**" is one or more persons occupying the Property pursuant to a Lease.
   1.7. "**Security Deposit**" is any interest free security deposit, cleaning deposit, prepaid rent deposit, or other sum advanced by a Tenant under terms that may require repayment by Owner or application against a future liability of such Tenant.

2. **TERM **

    2.1. This Agreement shall become effective from the date when the owner bought the package on Homzhub.com or handed over a set of keys of all the properties mentioned in Annexure A to Homzhub, whichever is later and shall continue in full force and effect until terminated in accordance with the terms of this Agreement. (“**Term**”);

3. **LETTING AND MANAGEMENT FEES**

**LETTING FEES FOR FIRST TERM:**

    3.1. In the event that Homzhub introduces a tenant who enters into a tenancy agreement to rent the owner’s property (the "Initial Agreement"), service fees become payable to Homzhub ("Fees for the Initial Tenure"). Refer clause for Homzhub outstanding fees.

    3.2. The expected rent, security deposit and other particulars mentioned in Annexure A are to viewed as a reference point and not as strict criteria since these particulars will vary with the change in market trend.

    3.3. Homzhub will search for prospective tenant(s) who match and agree to the terms mentioned in Annexure A. The final decision to accept the tenancy offer will be with the owner of the property. However, the owner should not discriminate the prospect(s) on the basis of race or creed.

    3.4. The Initial service fee is payable when the Lease agreement is signed by all parties or on the commencement of the tenancy whichever is earlier and charged as a percentage of the total rental value of the agreed term as specified in the tenancy agreement, as well as set out in the Fees Schedule table above.
    3.5. The Initial service fee is payable for any tenant introduced to the property by Homzhub, whether or not the tenancy is finalised by Homzhub.
    3.6. If the tenancy agreement is terminated in accordance with a break clause, Homzhub will refund any fees already received for the remaining period of the tenancy. The service fee will be refunded within 14 days of the tenant vacating the property only if Homzhub is no longer actively seeking for a prospective tenant for the vacant property, in which case the refund will be provided as a discount in the next billing cycle.
    3.7. Homzhub will endeavour to contact both the Owner and tenant before the end of the Initial Agreement to negotiate an extension of the tenancy, if so required.

    **LETTING FEES FOR RENEWAL**

    3.8. In the event that the tenant renews, extends, holds-over and/or enters into a new agreement for which rental income is received, service fee becomes payable to Homzhub ("Renewal Fee").
    3.9. The Renewal service fee is due and payable on the commencement of each Renewal taking place from the expiry of the Initial Agreement.
    3.10. Where a Renewal is for an agreed term, the Renewal service fee is charged as a percentage of the total rental value of that agreed term, subject to the Fees Schedule as presented in the table above.
    3.11. Where there is no agreed term for a Renewal, the Renewal service fee is charged as a percentage of the total rental value as if the Renewal would be for the same duration as the Initial Agreement.
    3.12. The schedule of Renewal service fees charged is as set out in the Fees Schedule table above. If the tenant vacates the property prior to the end of the period for which Renewal service fees has been paid in accordance with the Fees Schedule table above, Homzhub will refund the commission for the remaining period. The commission will be refunded within 14 days of the tenant vacating the property.
    3.13. Renewal service fee will be due in respect of Renewals where the original tenant remains in occupation. Where there is more than one tenant, Renewal service fee will be payable in accordance with the Fees Schedule table above, where any or all of them remain in occupation
    3.14. Renewal service fee will be due whether or not the renewal, extension, hold-over or new agreement with the tenant is negotiated by Homzhub.

4. **PROPERTY MANAGEMENT SERVICES**

    The Management Service includes all the provisions and terms of the Lettings Service.

    4.1. **_Minimum Period: _**The minimum period of our appointment to manage the property is **six months** where Homzhub is instructed to manage from the beginning or mid-term of the tenancy.
    4.2. **_Key-holding service: _**We require a set of keys in order to be able to manage your property effectively. These will be held locally in our secure system and made available to our approved suppliers or any other party authorised by you.
    4.3. **_Repairs and maintenance: _**Homzhub will attend to the day-to-day minor repairs and maintenance of the property and its contents. Homzhub shall have the right to engage independent contractors for performance of such of its duties hereunder as Homzhub deems necessary, but Homzhub shall have the responsibility for supervision of the performance of such duties. All contracts with independent contractors in excess of **_INR 3500/ US$50_** shall be subject to the prior written consent of Owner. However, in emergencies or wherever we consider it necessary, we will act to protect Owner’s interests without consultation.
    4.4. **_Termination: _**The service agreement can be terminated after this minimum period by either party giving **one months’** notice to the other, such notice not to expire before end of the minimum period. On the expiry of such notice, we will revert to the Lettings Service and the service fees payable will revert to those payable for the Lettings Services or those payable during Renewal, as appropriate.  
    4.5. **_Property Related Expenses:_ **A float of _I**NR 3500/ US$50**_ (or other amount to be agreed in writing) is required at the commencement and during the term of the management, to enable us to meet any expenditure on the Owner’s behalf. Homzhub cannot undertake to meet any outgoings beyond the funds we hold.
    4.6. Where instructed by the Owner and where we hold sufficient funds, Homzhub will pay ground rents, service charges, property taxes, gas and electricity bills, water rates and any regular outgoings out of the rental income. Homzhub will endeavour to query any obvious discrepancies, however, it must be understood that we are entitled to accept and pay, without question, demands and accounts that we believe to be in order.
    4.7. **_Property Inspections:_** We will undertake **One inspections** of the property each year. This inspection can only provide a high level examination and is not intended to be a structural survey. We cannot accept responsibility for hidden or latent defects.
    4.8. **_Inventory, Tenant on-boarding and off-boarding: _**Where instructed, Homzhub will arrange to draw up an inventory of your property's fixtures, fittings and contents, and compile a check-in report at the start of each tenancy. Homzhub does not accept liability for losses resulting from any errors or omissions within any inventory, check-in or check-out documents that are produced by a third party. Homzhub will arrange for the Tenant to be checked-out against the initial inventory report at the end of the tenancy and send the copy of the report.
    4.9. **_Management while the property is vacant:_** During void periods, Homzhub will continue to manage the property, however, cannot be held liable for any loss and/or damage arising from fire, flood or theft. If the Owner requires supplies to be turned off or disconnected during this period, Homzhub must receive instructions in writing and will arrange for the required contractor to attend at the Owner's expense.
    4.10. **_Purchase of items for property / Furnishing the property:_** Homzhub has access to suppliers who can deliver common household items to the property. **If, however, you require Homzhub to purchase items or furnish the property then our time on this will be charged per hour or percentage of the price thereof, or on per diem basis which would be communicated in writing to the owner before initiation of the work.**
    4.11. **_Liaising with third parties:_** Homzhub will liaise where necessary with the Owner's accountants, solicitors, PoA holders, managing agents and mortgagees etc..

5. **COLLECTION OF RENT ON BEHALF OF OWNER**

    Where instructed by the Owner, Homzhub will collect rent in accordance with the terms of the tenancy agreement.

    5.1. The Owner may direct Homzhub to stop collecting the rent by giving one month's notice in writing to Homzhub.
    5.2. Where Homzhub collects the rent, if the rent has not been paid five days after it falls due, Homzhub will endeavour to notify the Owner at the earliest possible opportunity, and will attempt to obtain payment from the tenant by means of telephone calls and a series of written notices.

6. **REMITTANCE OF FUNDS TO THE OWNER**
   6.1. Upon commencing the tenancy and in receipt of cleared funds from the tenant, Homzhub shall deposit, any money due to the owner within **three working days**, in a bank account provide by the Owner in this agreement.
   6.2. In some cases it may take up to ten working days to process the payment. We are not responsible for any bank charges that Owner incur as a result of delays in payment.
   6.3. Where Owner provide Homzhub with **India/Singapore** bank details, we use the NEFT/RTGS/GIRO inter-bank systems to make payments to your account and do not charge for this service. Where Homzhub is required to make payment by alternative methods (Telegraphic Transfer, or cheque) we will pass on any costs incurred in doing this to you.
   6.4. Any disbursements made by Homzhub pursuant to this Agreement shall be made out of the Monthly Rent collected, except as otherwise designated as expenses of the Homzhub. Owner agrees to make necessary operating funds available to Homzhub.
   6.5. Homzhub shall not be obligated to make any advance to the Owner’s designated account or to pay any amount except out of funds collected in the monthly rent, nor shall Homzhub be obligated to incur any extraordinary liability or obligation unless Owner shall furnish Homzhub with the necessary funds for the discharge thereof. If Homzhub shall voluntarily advance any amount of its own funds on behalf of Owner for the payment of any obligation or necessary expense connected with the maintenance or operation of the Property or otherwise, Owner authorizes Homzhub to deduct the dues from the following month’s rental.
   6.6. Notwithstanding any of the foregoing provisions or any similar provisions that follow, the prior written approval of the Owner will be required for any expenditure which exceeds **_INR 3500/ US$50_** in any one instance for litigation involving the Property, or labor, materials, or otherwise in connection with the maintenance and repair of the Property (including withdrawals from the replacement reserve to fund maintenance and repair of the Property). This limitation is not applicable for recurring expenses within the limits of the emergency repairs involving manifest danger to persons or property, or that are required to avoid suspension of any necessary service to the Property. In the latter event, the Homzhub will inform the Owner of the facts as promptly as possible.

7. **SECURITY DEPOSIT**

    7.1. Where instructed by the Owner, Homzhub shall be entitled to collect an interest free refundable Security Deposit from tenant(s) to be retained at its end. Homzhub will not be obligated to pay the same to the Owner.
    7.2. Homzhub also undertakes to promptly return the Security Deposit to the tenant(s) upon termination of lease/license, after making necessary deductions.
    7.3. In the event that the Owner, hold the interest free refundable Security deposit, the Owner agrees to fully indemnify Homzhub against any claim by the tenant howsoever arising, as a result of Owner holding the deposit.

8. **HOMZHUB OUTSTANDING FEES**

    8.1. The fee that Homzhub shall be entitled to receive for the services rendered under this Agreement and as suitable consideration thereof, the Owner shall pay Homzhub as detailed in Homzhub Services & Fees Schedule.

    8.2. The Owner agrees that, where any of Homzhub’ fees and/or charges remain outstanding for more than seven days, Homzhub may use any sums obtained or held on the owner’s behalf to pay the outstanding sums, including rental payments on this or any other property on which Homzhub is instructed.

9. **TENANT BACKGROUND CHECKS**

    9.1. Where the Owner requested for background check services, Homzhub will take reasonable steps to attempt and verify the identity of potential tenants through – Identity and address validation, Criminal history validation**, **Credit history validation **and** **Employment history validation, from publicly available sources and/or sources provided by the owners and tenants.
    9.2. The Owner acknowledge and agree that the Service may contain content ("**Service Content**") that is protected by copyright, patent, trademark, trade secret or other proprietary rights and laws. Except as expressly authorized by the Homzhub, the Owner agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Service Content, in whole or in part. In connection with the Owner’s use of the Service, the Owner shall not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. Any use of the Service or the Service Content other than as specifically authorized herein is strictly prohibited. The technology and software underlying the Service or distributed in connection therewith is the property of Homzhub, its affiliates and our partners (the "**Software"). The Owner agree not to copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Software. The Homzhub reserves any rights not expressly granted herein.

10. **INDEMNIFICATION**

    10.1. The Owner agrees to indemnify, defend, and hold Homzhub and its directors, officers, employees, shareholders, subsidiaries, affiliates, successors, and assigns (the “**Indemnified Party**”) harmless from and against any and all liabilities, losses, damages, costs, fines, penalties, interest, and expenses (including, without limitation, attorneys’ and other professionals’ fees) on account of any claim, suit, action, demand, or proceeding made or brought against the Indemnified Party, or on account of the investigation, defense, or settlement thereof (hereinafter referred to as “Claims and Losses”), arising out of or in connection with: (a) performance of the Services violating the applicable Laws; (b) breach of the Owner’s covenants; and (c) breach of the Owner’s representations and warranties; and (d) breach of the Owner’s other obligations set out in this Agreement.

    10.2. **_<span style="text-decoration:underline;">Limitation of Liability</span>:_** Homzhub shall not be liable under or related to the Agreement for any of the following, whether based on contract, tort or any other legal theory, even if a party has been advised of the possibility of such damages: (i) any incidental, punitive, special, exemplary, consequential, or other indirect damages of any type or kind; or (ii) the Owner’s or any third party’s property damage, or loss or inaccuracy of data, or loss of business, revenue, profits, use or other economic advantage except for Homzhub’s obligations to pay amounts due pursuant to any clause under the Agreement, and subject to any limitations or other provisions contained in the Agreement which are applicable thereto. In no event shall the liability of the Homzhub or its affiliates under the Agreement exceed the amount of the fees actually paid to or due to the Homzhub hereunder in the **1 (one) **month period immediately preceding the event giving rise to such claim.

11. **CONFIDENTIALITY**

    11.1. The Owner agrees not to, during or subsequent to the Term of this Agreement, disclose or use Homzhub Confidential Information (defined below). The Parties agree that the Confidential Information shall remain the sole property of Homzhub.
    11.2. For the purposes of this Agreement, the term “**Confidential** **Information**” shall mean any matter, information, or material relating to Homzhub’ affairs, whether or not arising under this Agreement, coming within the Owner’s knowledge either in connection with his relationship with Homzhub, rendering the Services, or otherwise, including, without limitation, any confidential or proprietary information of Owner’s suppliers and vendors. Confidential Information includes, without limitation, (i) the terms of this Agreement, (ii) items that are marked or identified, orally or in writing, as Owner’s confidential or proprietary information, or items which the Homzhub should recognize from the circumstances surrounding the disclosure as being confidential, (iii) information and details concerning the building construction materials and office equipment, (iv) all communications between Homzhub and Owner related to this Agreement, (v) any copies, summaries, extracts, and other forms of the foregoing, and (vi) any such information that may have been disclosed prior to the full execution and delivery of this Agreement.  
    11.3. The Homzhub will retain personal data that it will process on behalf of the Owner for as long as needed to provide Services to the Owner. The Homzhub will retain and use this personal information as necessary to comply with its legal obligations, resolve disputes, and enforce its agreements. The Homzhub will operate through a global network of corporate offices, subscriptions, service centers, and data centers, it may be necessary to transfer the Owner information outside of the Owner country of residence or nationality, where it was originally collected. The information that the Owner provides that the Homzhub during the course of a subscribing the Services or through the provision of any other services may be transferred to any of the Homzhub or affiliated entities around the world for the purposes of carrying out or facilitating these services. It will also be necessary to transfer this information to third parties, including, without limitation, the Homzhub’ franchisees, partners and third-party service providers.

12. **TERMINATION**

    12.1. This Agreement shall be terminated automatically and immediately upon destruction, condemnation, sale, exchange, or other disposition (excluding any mortgage or refinancing) of the Property by Owner.  
    12.2. This Agreement will terminate by mutual written consent of Homzhub and Owner.
    12.3. This Agreement shall terminate upon the occurrence of any of the following circumstances, which shall be considered a default: 1. The filing of a voluntary petition of bankruptcy or insolvency or a petition for reorganization under any bankruptcy law by either Owner or Homzhub; 2. The entering of an order, judgment or decree by any court of competent jurisdiction, on the application of a creditor, adjudicating either Owner or Homzhub a bankrupt or insolvent or approving a petition seeking reorganization or appointing a receiver, trustee or liquidator of all or a substantial part of such party's assets, and such order, judgment, or decree shall continue unstayed and in effect for a period of **one month**; or 3. The failure of Homzhub to perform, keep, or fulfill any of its duties or to comply with the covenants, undertakings, obligations, or conditions set forth in this Agreement, and the continuance of any such default for a period of **one month** after written notice of such failure. 4. The failure of Owner to make available sufficient funds to maintain the Property in compliance with applicable state and local laws, and such failure to provide funding continues for a period of **one month** after Homzhub provides Owner with written notice of the need for such funds.  
    12.4. Termination or expiry of this Agreement shall not relieve the Owner of any obligation or liability accrued prior to the date of such termination or expiry nor shall expiration or termination of the Agreement relieve the Owner from any liability arising from any breach of this Agreement.
    12.5. Under no circumstances will the Homzhub be liable in any way for any content posted by third parties, including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed or otherwise transmitted via the Service. The Owner acknowledge that the Homzhub does not pre-screen content, but that Homzhub and its designees shall have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Service. Without limiting the foregoing, Homzhub and its designees shall have the right to remove any content that violates the terms of this Agreement or is deemed by the Homzhub, in its sole discretion, to be otherwise objectionable. The Owner agree that it must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content. The Owner’s use of any information or materials on this website is entirely at its own risk, for which the Homzhub shall not be liable. It shall be the Owner’s own responsibility to ensure that any products, Services or information available through this website meet its specific requirements.
    12.6. The Owner will be responsible for maintaining the confidentiality of the password and account, if any, and will be fully responsible for any and all activities that occur under its password or account. The Owner shall (a) immediately notify the Homzhub of any unauthorized use of the password or account or any other breach of security, and (b) ensure that it exits from its account at the end of each session when accessing the Service. The Homzhub will not be liable for any loss or damage arising from your failure to comply in this regard.
    12.7. The Owner shall promptly notify the Homzhub of all Confidential Information in its possession and in accordance with Homzhub’ instructions, shall promptly deliver all such Confidential Information. Further within **5(five)** days of termination or expiry of this Agreement, the Owner shall furnish to Homzhub a written notice, certifying that all Confidential Information in its possession under the terms of this Agreement has either been returned to the Homzhub or destroyed as per the instructions of Homzhub, and no copies or portions thereof remain in the possession of the Owner and its employees so far as practicable, erase all such Confidential Information from any computer, word-processor or other device containing such information.  
    12.8. The Owner shall immediately cease to make any representations that it is directly or indirectly associated with or in any way interested in the business of the Homzhub.
    12.9. The Owner shall be obliged to pay, within **5(five)** days of the date of expiry of the Agreement, all amounts owing to the Homzhub for Services completed and accepted by Owner, and related expenses incurred by the Homzhub, if any. Notwithstanding the foregoing, Owner shall not have the right to withhold payment of all or any amounts owing to the Homzhub upon early termination of the Agreement caused by a breach by the Owner of the terms hereof.
    12.9. The Homzhub reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without the notice of the Owner. The Owner agrees that the Homzhub shall not be liable to the Owner or to any third party for any modification, suspension or discontinuance of the Service.
    12.10. Upon termination of this Agreement for any reason, Homzhub shall deliver to Owner immediately upon termination (or upon Homzhub’ subsequent receipt or acquisition) the following with respect to the Property: 1. Any Security Deposits or other monies belonging to Owner held by Homzhub on Owner's behalf; and 2. All records, contracts, Leases, receipts for deposits, unpaid bills, and other papers or documents relating to the Property.
    12.11. Within 1(**one) month** after the termination of this Agreement, Homzhub shall close all accounts and pay the balances or assign all certificates of deposit regarding the Property to Owner. Within 1(**one) month** after the termination of this Agreement, Homzhub shall deliver to Owner all plans and surveys of the Property in its possession and all books and records, keys, reports, files, Leases, contracts, and all other written material and property concerning the Property. Within 1(**one) month** after the termination of this Agreement, Homzhub shall submit to Owner all reports, and Homzhub and Owner shall account to each other with respect to all matters outstanding as of the date of termination. Upon Owner's request, Homzhub shall assign to Owner all contracts requested by Owner concerning the Property, to the extent permitted by such contracts, and shall cooperate (at no expense to Homzhub) with Owner in connection with the transition to a new property manager.

13. **COOPERATION**

    13.1. If any claims, demands, suits, or other legal proceedings that arise out of any of the matters relating to this Agreement be made or instituted by any person against either Owner or Homzhub, Owner or Homzhub shall give to each other all pertinent information and reasonable assistance in the defense or other disposition thereof, at its sole expense.

14. **CONSENT**

    14.1. Whenever in this Agreement the consent or approval of Homzhub or Owner is required, such consent or approval shall not be unreasonably withheld or delayed. Such consent shall be in writing and shall be duly executed by an authorized officer or Homzhub for the party granting such consent or approval; provided, however, notwithstanding anything in this Agreement to the contrary, if such consent or approval would be required for Homzhub to comply with the Requirements, Homzhub shall not be responsible for a failure to comply with the requirements as a result of Owner's refusal or unreasonable delay to so consent or approve.

15. **ELECTRONIC DOCUMENTATION**
    15.1. Contracts which have been signed electronically (whether by e-signature, fax, email or website authentication) are binding and admissible in evidence. For convenience, we may ask you or any prospective tenants to sign documents electronically.

16. **OWNERSHIP OF INTELLECTUAL PROPERTY**
    16.1. The Owner acknowledges and agrees that this Agreement does not confer them any right, title or interest express or implied in or to the intellectual property rights of Homzhub. All rights in such intellectual property solely rest in Homzhub, including, without limitation to the Confidential Information referred to in Clause 9 above. The Owner further acknowledges that this Agreement does not grant him any license, whether express or implied to use the intellectual property rights of Homzhub in any manner whatsoever.  
    16.2. The Owner shall not use in advertising, publicity, promotion, marketing or other activity, anything that represents or is likely to interpreted as representing Homzhub’ corporate identity or any affiliate corporate identity, such as, without limitation: (i) any name, model numbers, trademarks, trade names, trade dress, service marks or other designation of the Homzhub or its affiliates or any translation thereof or words, colors, triangular shapes, marks or representations confusingly similar thereto: or (ii) owned by Homzhub without the prior written consent of Homzhub.

17. **MISCELLANEOUS**

    17.1. **_Special Power of Attorney:_** Owner authorizes Homzhub as attorney-in-fact for Owner to enter into and execute Leases and rental agreements with respect to the Property on forms approved by Owner, to collect rents and other funds due to Owner, in Homzhub's name on Owner's behalf, and to establish and make deposits into and withdrawals from the Security Deposit Account and Owner’s Designated Account in accordance with the terms of this Agreement.
    17.2. **_Entire Agreement:_** This Agreement constitutes the entire Agreement between Homzhub and Owner, and no amendment, alteration, modification, or addition to this Agreement shall be valid or enforceable unless expressed in writing and signed by the parties hereto and unless such amendment, alteration, modification, or addition has been consented to in writing by the Parties.
    17.3. **_Severability: _**If any provision of this Agreement is rendered void, illegal or unenforceable in any respect under the applicable law, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired. Should any provision of this Agreement be or become unenforceable, the Parties to this Agreement shall use reasonable endeavours to agree upon a new provision which shall as nearly as possible have the same commercial effect as the ineffective provision.
    17.4. **_Relationship:_** Nothing contained in this Agreement shall be construed to create a relationship of employer and employee between Owner and Homzhub, it being the intent of the parties hereto that the relationship created hereby is that of an independent contractor. Nothing contained herein shall be deemed to constitute the Owner and Homzhub relationship as a partnership or joint venture.
    17.5. **_Governing Law:_** This Agreement shall be governed by and interpreted in accordance with the laws of the state of Nagpur, India.
    17.6. **_Attorney Fees: _**If any judicial remedy is necessary to enforce or interpret any provision of this Agreement, the prevailing party shall be entitled to reasonable attorney fees, costs and other expenses, at trial and on appeal.
    17.7. **_Successors and Assigns:_** This Agreement shall inure to the benefit of and constitute a binding obligation upon Owner and Homzhub and their respective successors and assigns; provided, however, that Homzhub shall not assign this Agreement or any of its duties hereunder, without the prior written consent of Owner.
    17.8. **_Survival: _**The obligations provided for in Clause 11 (Confidentiality), Clause 12 (Termination), Clause 16 (Ownership of Intellectual Property), Clause 17.3 (Severability), Clause 17.5 (Governing Law and Jurisdiction) and this Clause shall survive the termination of this Agreement.
    17.9. **_Enforceability:_** The invalidity of any clause, part, or provision of this Agreement shall not affect the validity of the remaining portions thereof. Owner's remedies under this Agreement are cumulative, and the exercise of one remedy shall not be deemed an election of remedies nor foreclose the exercise of Owner's other remedies. No waiver by Owner of any breach of this Agreement shall be deemed to be a waiver of any other or subsequent breach. Owner or Homzhub may apply to any court, state or federal, for specific performance of this Agreement, for an injunction against any violations of this Agreement, or for such other relief as may be appropriate, since the injury arising from a default under any of the terms of this Agreement would be irreparable and the amount of damage would be difficult to ascertain. However, for damages claims, the parties agree they will first seek voluntary mediation in the case of any dispute, claim, counter-claim, defense, controversy (collectively, “**Disputes**”) between the parties concerning this agreement. The party initiating mediation shall choose a neutral mediator and propose times and dates for mediation. If the second party objects to the choice of mediator, a second mediator will be chosen. The mediation shall be conducted under the then existing rules of Nagpur, India Arbitration Association. The mediation shall take place in Nagpur, India only and mediator fees shall be shared equally between the parties. The resolution of the disputes shall be memorialized in writing. If mediation is unsuccessful, the disputes may be raised in any court with jurisdiction over this matter.
    17.10. **_Superseding Clause: _**This Agreement comprises the entire understanding between the Parties with respect to the subject matter hereof, and supersedes all prior agreements and understandings, both written and oral, between the Parties.
    17.11. **_No Third-Party Beneficiaries:_** Nothing in this Agreement is intended to benefit any person or entity other than Owner or Homzhub, and this Agreement shall not be construed to provide any other persons or entities with any rights or remedies against the parties. No one other than Owner or Homzhub shall be entitled to rely on the implementation or enforcement of any term of this Agreement.
    17.12. **_Cost_**: Each Party shall pay its own costs and expenses in relation to the negotiation, preparation, and implementation of this Agreement, including the fees and disbursements of their respective legal counsels. The stamp duty payable on this Agreement shall be borne and paid by Owner.
    17.13. **_Counterparts_**: This Agreement may be executed in one or more counterparts, each of which shall be deemed an original but all of which together shall constitute one and the same instrument and the Parties may execute this Agreement by signing any one or more of such originals or counterparts.
`;
