enum envKeys {
  REACT_NATIVE_APP_API_BASE_URL = '',
  REACT_NATIVE_APP_PLACES_API_BASE_URL = '',
  REACT_NATIVE_APP_OTP_LENGTH = '',
  REACT_NATIVE_APP_STORAGE_SECRET = '',
  REACT_NATIVE_CONFIG_MODE = '',

  REACT_NATIVE_MAIN_URL = '',
  REACT_NATIVE_ANDROID_APP_ID = '',
  REACT_NATIVE_IOS_APP_ID = '',
  REACT_NATIVE_APP_STORE_ID = '',

  //keys
  REACT_NATIVE_APP_PLACES_API_KEY = '',
  REACT_NATIVE_APP_RAZOR_API_KEY = '',
  REACT_NATIVE_APP_MIXPANEL_KEY = '',
  REACT_NATIVE_APP_YOUTUBE_API_KEY = '',

  // client-ID
  REACT_NATIVE_APP_GOOGLE_WEB_CLIENT_ID = '',
  REACT_NATIVE_APP_GOOGLE_IOS_CLIENT_ID = '',

  // store-url
  REACT_NATIVE_APP_APPLE_STORE_URL = '',
  REACT_NATIVE_APP_GOOGLE_PLAYSTORE_URL = '',

  // firebase
  REACT_NATIVE_FIREBASE_API_KEY = '',
  REACT_NATIVE_FIREBASE_PROJECT_ID = '',
  REACT_NATIVE_FIREBASE_APP_ID = '',
  REACT_NATIVE_FIREBASE_DATABASE_URL = '',
  REACT_NATIVE_FIREBASE_MESSAGING_SENDER_ID = '',
  REACT_NATIVE_FIREBASE_AUTH_DOMAIN = '',
  REACT_NATIVE_FIREBASE_STORAGE_BUCKET = '',
  REACT_NATIVE_FIREBASE_DYNAMIC_URL = '',

  // Release keys
  REACT_NATIVE_APP_UPLOAD_STORE_FILE = '',
  REACT_NATIVE_APP_UPLOAD_KEY_ALIAS = '',
  REACT_NATIVE_APP_UPLOAD_STORE_PASSWORD = '',
  REACT_NATIVE_APP_UPLOAD_KEY_PASSWORD = '',

  // App mode
  REACT_NATIVE_APP_MODE = '',
}
