export const RouteNames = {
  publicRoutes: {
    APP_BASE: '/',
    ABOUT: '/about',
    FEATURED: '/featured',
    PRICING: '/pricing',
    LOGIN: '/login',
    SIGNUP: '/signup',
    SERVICE_PLANS_DETAIL: '/service-plans/:plansId',
    OTP_VERIFICATION: '/otp',
    MOBILE_VERIFICATION: '/mobileVerification',
    TERMS_CONDITION: '/terms&Condition',
    TERMS_SERVICES_PAYMENTS: '/terms-Services&Payments',
    TERMS_PROPERTY_MANAGEMENT: '/property-management-terms',
    PRIVACY_POLICY: '/privacyPolicy',
    UPLOAD: '/upload',
    MAHARASHTRA_CONNECT: '/maharashtra_connect',
    FAQS: '/faqs',
    MEMBERSHIP_PLANS: '/membership-plans',
    PROPERTY_DETAIL: '/home/propertyDetail/:propertyName',
    ERROR404: '/*',
    ERROR504: '/gateway-timeout',
    ERROR: '/error',
  },
  protectedRoutes: {
    /* Mention protected route names here */
    DASHBOARD: '/home',
    FINANCIALS: '/home/financials',
    PORTFOLIO: '/home/portfolio',
    ADD_PROPERTY: '/home/addProperty',
    PORTFOLIO_ADD_PROPERTY: '/home/portfolio/addProperty',
    ADD_LISTING: '/home/nextActions',
    SEARCH_PROPERTY: '/home/searchProperty',
    PROPERTY_VIEW: '/home/propertyView',
    PROPERTY_SELECTED: '/home/portfolio/propertySelected/:propertyName',
    SAVED_PROPERTIES: '/home/savedProperties',
    PROPERTY_VISITS: '/home/propertyVisits',
    OFFERS: '/home/offers',
    OFFERS_LISTED_PROPERTY: '/home/offers/:listingId',
    // WRITE YOUR routes here accordingly
    NOTIFICATIONS: '/home/notifications',
    TICKETS: '',
    KYC_DOCUMENTS: '',
    NEW_LAUNCHES: '',
    MARKET_TRENDS: '',
    SELECT_PROPERTY: '/home/marketPlace/selectProperty',
    SELECT_SERVICES: '/home/marketPlace/selectServices',
    VALUE_ADDED_SERVICES: '/home/marketPlace',
    SERVICE_TICKETS: '/home/serviceRequests',
    SERVICE_TICKET_DETAILS: '/home/serviceRequests/serviceRequestDetails',
    SETTINGS: '/home/settings',
    MANAGE_SUBSCRIPTION: '',
    PAYMENT_METHODS: '',
    LOGOUT: '',
    HELP_SUPPORT: '/home/help&Support',
    REFER_EARN: '/home/refer&Earn',
    PROFILE: '/home/profile',
    PROTECTEDERROR404: '/home/*',
  },
};

export enum ScreensKeys {
  Dashboard = 'Dashboard',
}
